name: CI-CD main
on:
  push:
    branches:
      - main
env:
  SSH_HOST: 164.92.91.181
  SSH_USER: root

jobs:
  ssh-to-ec2:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USER }}
        password: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
            cd /var/www/gogo_admin
            git pull origin main
            yarn
            yarn build
